config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'gachas#index'
  resources :gachas, only: [:create]
  resources :recipes, only: [:index, :show]
  resources :ingredients, only: [:index]

  post '/ingredients/checked' => "ingredients#check"
  post '/recipes/checked' => "recipes#check"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    # TODO(Tatsuemon): 厳重なvalidation
    # validation
    validates :title, presence: true
    validates :description, presence: true
    validates :step, presence: true

    has_many :recipe_tags, dependent: :destroy
    has_many :tags, through: :recipe_tags

    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients

    # TODO(Tatsuemon): has_manyの記述
    # has_many :recipe_groups, 

    # belongs_to :saturday_recipe, class_name: "Recipe", foreign_key: "saturday_recipe_id"
    # belongs_to :sunday_recipe, class_name: "Recipe", foreign_key: "sunday_recipe_id"
    # belongs_to :monday_recipe, class_name: "Recipe", foreign_key: "monday_recipe_id"
    # belongs_to :tuesday_recipe, class_name: "Recipe", foreign_key: "tuesday_recipe_id"
    # belongs_to :wednesday_recipe, class_name: "Recipe", foreign_key: "wednesday_recipe_id"
    # belongs_to :thursday_recipe, class_name: "Recipe", foreign_key: "thursday_recipe_id"
    # belongs_to :friday_recipe, class_name: "Recipe", foreign_key: "friday_recipe_id"
end

app/models/tag.rb
class Tag < ApplicationRecord
    # validation
    validates :name, presence: true

    has_many :recipe_tags, dependent: :destroy
    has_many :recipes, through: :recipe_tags
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authentification_user?

    include YobiDate
    # 一週間の献立を表示
    def index
        today = Date.today
        @recipe_group = RecipeGroup.find_by(user_id: @current_user.id, start_date: get_saturday(today))
        return redirect_to "/" if @recipe_group.blank?
        @recipes = @recipe_group.get_recipes()
        @yobis = ["土曜日", "日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日"]
    end

    # レシピの詳細
    def show
        @recipe = Recipe.includes(:ingredients).find(params[:id])
    end

    # 1週間のレシピで食べるものの選定
    def check
        today = Date.today()
        yobi_number = params[:id].to_i
        checked = params[:checked] == "true"
        recipe_group = RecipeGroup.find_by(user_id: @current_user.id, start_date: get_saturday(today))
        params = recipe_group.get_cook_params(yobi_number, checked)
        # updateはsaveを読んでるため, recipesを読みこんでいる
        recipe_group.update!(params)
        render json: { code: 200 }
    end

    private
end

app/views/recipes/index.html.erb
<h1>
    あなたの一週間分の食事です
</h1>

<ul>
    <% @recipes.each_with_index do |recipe, i| %>
    <li>
        <div><%= @yobis[i] %>（<%= @recipe_group.start_date + i %>）</div>
        <%= link_to  recipe.title, recipe_path(recipe) %>
        （説明）<%= recipe.description %>

        <div>
            <%= check_box :recipes, :recipe_ids, { checked: @recipe_group.get_cook[i], title: "#{i}", id: "recipe_#{recipe.id}" } %>
            この料理をつくる？？
        </div>
        <div><%= image_tag recipe.image_url, style: "height: 20rem; width: 30rem;" %></div>
    </li>
    <% end %>
</ul>

<%= button_to "ガチャに戻る", '/', method: :get %>
<%= button_to "買い物リスト", '/ingredients', method: :get %>

app/views/recipes/show.html.erb
<h1>
    レシピの詳細
</h1>

<div>
    <h2>
        料理名: <%= @recipe.title %>
    </h2>

    <div><%= image_tag @recipe.image_url, style: "height: 20rem; width: 30rem;" %></div>

    <h4>
        説明: <%= @recipe.description %>
    </h4>

    <h4>
        材料:
    </h4>
    <ul>
        <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
            <li>
                <%= recipe_ingredient.ingredient.name %> （<%= recipe_ingredient.amount %> <%= recipe_ingredient.unit %>）
            </li>
        <% end %>
    </ul>

    <h4>
        工程: <%= @recipe.step %>
    </h4>
</div>

<%= button_to "一週間の食事に戻る", '/recipes', method: :get %>